---
casks:
  aerospace:
  bitwarden:
  copilot-cli:
  discord:
  figma:
  font-caskaydia-cove-nerd-font:
  font-fira-code-nerd-font:
  font-hack-nerd-font:
  font-juliamono:
  font-maple-mono:
  font-maple-mono-nf:
  font-monaspace:
  font-symbols-only-nerd-font:
  ghostty:
  gimp:
  kdiff3:
  keycastr:
  licecap:
  macdown:
  ngrok:
  postman:
  spotify:
