---
- name: link dotfiles
  file:
    src: "{{ item.src | expanduser }}"
    dest: "{{ item.dest | expanduser }}"
    state: link
    force: '{{ item.force | default("no") }}'
  loop:
    - {
        src: "~/.dotfiles/config/gtk-3.0/settings.ini",
        dest: "~/.config/gtk-3.0/settings.ini",
      }
    - { src: "~/.dotfiles/config/aws/config", dest: "~/.aws/config" }
    - {
        src: "~/.dotfiles/config/karabiner/karabiner.json",
        dest: "~/.config/karabiner/karabiner.json",
        force: true,
      }
    - { src: "~/.dotfiles/config/gitconfig", dest: "~/.gitconfig", force: true }
    - {
        src: "~/.dotfiles/config/gh/config.yml",
        dest: "~/.config/gh/config.yml",
      }
    - {
        src: "~/.dotfiles/config/starship.toml",
        dest: "~/.config/starship.toml",
      }
    - {
        src: "~/.dotfiles/config/aerospace",
        dest: "~/.config/aerospace",
        force: true,
      }
    - {
        src: "~/.dotfiles/config/terminator/config",
        dest: "~/.config/terminator/config",
      }
    - { src: "~/.dotfiles/curlrc", dest: "~/.curlrc" }
    - { src: "~/.dotfiles/gtkrc-2.0", dest: "~/.gtkrc-2.0" }
    - { src: "~/.dotfiles/wgetrc", dest: "~/.wgetrc" }
    - { src: "~/.dotfiles/xinitrc", dest: "~/.xinitrc" }
    - { src: "~/.dotfiles/zshrc", dest: "~/.zshrc" }
    - { src: "~/.dotfiles/zprofile", dest: "~/.zprofile" }
    - { src: "~/.dotfiles/config/kitty", dest: "~/.config/kitty", force: true }
    - {
        src: "~/.dotfiles/config/lazygit/config.yml",
        dest: "~/Library/Application Support/lazygit/config.yml",
        force: true,
      }
    - { src: "~/.dotfiles/config/nvim", dest: "~/.config/nvim", force: true }
    - { src: "~/.dotfiles/config/tmux", dest: "~/.config/tmux", force: true }
    - { src: "~/.dotfiles/config/sesh", dest: "~/.config/sesh", force: true }
    - {
        src: "~/.dotfiles/config/ghostty",
        dest: "~/.config/ghostty",
        force: true,
      }
    - {
        src: "~/.dotfiles/config/zellij/config.kdl",
        dest: "~/.config/zellij/config.kdl",
        force: true,
      }
    - {
        src: "~/.dotfiles/config/wezterm",
        dest: "~/.config/wezterm",
        force: true,
      }
    - {
        src: "~/.dotfiles/config/gh-dash",
        dest: "~/.config/gh-dash",
        force: true,
      }
  tags: links
