---
- name: delete default files
  file:
    path: ~/.config/kitty
    state: absent

- name: link dotfiles
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
    force: '{{ item.force | default("no") }}'
  loop:
    - {
        src: '~/.dotfiles/config/gtk-3.0/settings.ini',
        dest: '~/.config/gtk-3.0/settings.ini',
      }
    - {
        src: '~/.dotfiles/config/aws/config',
        dest: '~/.aws/config',
      }
    - {
        src: '~/.dotfiles/config/karabiner/karabiner.json',
        dest: '~/.config/karabiner/karabiner.json',
        force: yes
      }
    - {
        src: '~/.dotfiles/config/lvim/config.lua',
        dest: '~/.config/lvim/config.lua',
        force: yes,
      }
    - { src: '~/.dotfiles/config/gitconfig', dest: '~/.gitconfig', force: yes }
    - {
        src: '~/.dotfiles/config/gh/config.yml',
        dest: '~/.config/gh/config.yml',
      }
    - {
        src: '~/.dotfiles/config/starship.toml',
        dest: '~/.config/starship.toml',
      }
    - {
        src: '~/.dotfiles/config/terminator/config',
        dest: '~/.config/terminator/config',
      }
    - { src: '~/.dotfiles/curlrc', dest: '~/.curlrc' }
    - { src: '~/.dotfiles/gtkrc-2.0', dest: '~/.gtkrc-2.0' }
    - { src: '~/.dotfiles/wgetrc', dest: '~/.wgetrc' }
    - { src: '~/.dotfiles/xinitrc', dest: '~/.xinitrc' }
    - { src: '~/.dotfiles/zshrc', dest: '~/.zshrc' }
    - { src: '~/.dotfiles/config/kitty', dest: '~/.config/kitty', force: yes }
    - { src: '~/.dotfiles/config/lvim/lua', dest: '~/.config/lvim/lua', force: yes }
    - { src: '~/.dotfiles/config/lvim/after', dest: '~/.config/lvim/after', force: yes }
    - { src: '~/.dotfiles/config/nvim', dest: '~/.config/nvim', force: yes }
