---
- name: Playbook to manage mhuggins7278 dotfiles (https://github.com/mhuggins7278/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    - name: Make sure dotfiles are present
      git:
        repo: https://github.com/mhuggins7278/dotfiles.git
        dest: ~/.dotfiles

    - name: Allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
        insertafter: '^%admin\tALL=\(ALL\) ALL'
        validate: "visudo -cf %s"
      become: yes
      when: sudo_without_password and ansible_os_family == "Darwin"

    - name: Enable tty_tickets
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "Defaults tty_tickets"
        validate: "visudo -cf %s"
      become: yes
      when: ansible_os_family == "Darwin"

    - name: Install oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.local/share/oh-my-zsh
        update: yes

    - name: Install tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/tpm
        update: yes

    - name: Create folder
      tags:
        - links
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "~/.cache/bash/"
        - "~/.cache/vim/"
        - "~/.cache/vim/backup/"
        - "~/.cache/vim/dein/"
        - "~/.cache/vim/swap/"
        - "~/.cache/vim/undo/"
        - "~/.cache/wget/"
        - "~/.config/gtk-3.0"
        - "~/.config/gh"
        - "~/.aws/"
        - "~/.config/karabiner/"
        - "~/.config/planetscale/"
        - "~/.config/mssqlcli/"
        - "~/.config/terminator/"
        - "~/.config/tmux/"
        - "~/.config/zellij/"
        - "~/.config/wezterm/"
        - "~/.config/aerospace/"
        - "~/.config/sesh/"
        - "~/.local/share/zsh/"
        - "~/Library/Application Support/Code/User/"
        - "~/Library/Application Support/layzgit/"
        - "~/github/"
        - "~/github/glg/"
        - "~/github/mhuggins7278/"
        - "~/github/LearnBuildTeach/"

    - include_tasks: tasks/packages.yml
      tags:
        - packages

    - include_tasks: tasks/shells.yml
      tags:
        - shells

    - include_tasks: tasks/link_files.yml
      tags: links

    - include_tasks: tasks/macos_defaults.yml
      when: ansible_os_family == "Darwin"
      tags:
        - macos_defaults

  handlers:
    - name: Kill Dock
      command: killall Dock

    - name: Kill Finder
      command: killall Finder

    - name: Kill Transmission
      command: killall Transmission
      ignore_errors: yes

    - name: Kill Terminal
      command: killall Terminal
      ignore_errors: yes
