git:
  parseEmoji: true
os:
  editPreset: 'vim' # as an example
customCommands:
  - key: "C"
    command: "gitmoji -c"
    description: "commit with gitmoji"
    context: "files"
    loadingText: "opening gitmoji commit tool"
    subprocess: true
  - key: "c"
    command: "cz commit"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
