promptToReturnFromSubprocess: false
git:
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --line-numbers --side-by-side --paging=never
gui:
  nerdFontVersion: "3"
os:
  editPreset: "nvim" # as an example
customCommands:
  - key: "C"
    command: "gitmoji -c"
    description: "commit with gitmoji"
    context: "files"
    loadingText: "opening gitmoji commit tool"
    subprocess: true
  - key: "c"
    command: "cz commit"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "O"
    command: "nvim -c ':Octo pr create'"
    context: "localBranches"
    loadingText: "Loading Octo"
    description: "Open pull request with Octo"
    subprocess: true
