#!/usr/bin/env bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
SKETCHYBAR="/opt/homebrew/bin/sketchybar"

##### Catppuccin Mocha Color Palette #####
# https://github.com/catppuccin/catppuccin
MAUVE=0xffcba6f7
TEXT=0xffcdd6f4
BASE=0xff1e1e2e
CRUST=0xff11111b

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

"$SKETCHYBAR" --bar position=top height=20 blur_radius=30 color="$CRUST"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color="$TEXT"
  label.color="$TEXT"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
"$SKETCHYBAR" --default "${default[@]}"

##### Adding AeroSpace Workspace Indicator #####
# Display current AeroSpace workspace

"$SKETCHYBAR" --add event aerospace_workspace_change \
           --add item aerospace left \
           --set aerospace \
           icon.padding_left=7 \
           icon.padding_right=7 \
           icon.color=$BASE \
           background.color=$MAUVE \
           background.drawing=on \
           background.corner_radius=5 \
           background.height=18 \
           label.drawing=off \
           script="$PLUGIN_DIR/aerospace.sh" \
           --subscribe aerospace aerospace_workspace_change

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

"$SKETCHYBAR" --add item chevron left \
           --set chevron icon= label.drawing=off

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

"$SKETCHYBAR" --add item spotify center \
           --set spotify update_freq=5 script="$PLUGIN_DIR/spotify.sh" \
                          click_script="osascript -e 'tell application \"Spotify\" to playpause'" \
           --add item memory right \
           --set memory update_freq=30 script="$PLUGIN_DIR/memory.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           --add item clock right \
           --set clock update_freq=30 icon= script="$PLUGIN_DIR/clock.sh"

##### Force all scripts to run the first time (never do this in a script) #####
"$SKETCHYBAR" --update
