// Copyright (c) 2026 Edward Luo. All rights reserved.
// This file is part of Vibe Island, a proprietary product.
// Unauthorized reproduction or distribution is prohibited.
// vibe-island-plugin-marker w1r1 — auto-generated by Vibe Island

import { Socket } from "net";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const SOCKET = require("os").homedir() + "/.vibe-island/run/vibe-island.sock";

const _VI_SOURCE = "opencode";

const _VI_SESSION_PREFIX = "opencode";
const _VI_ENV_PREFIX = "OPENCODE";
const _VI_DIRECTORY_HEADER = "x-opencode-directory";
const _VI_AUTH_USERNAME = "opencode";
const _VI_DESKTOP_BUNDLE_ID = "ai.opencode.desktop";
const _VI_GLOBAL_EVENT_BRIDGE = "auto";

const WIRE = 1;
const RAW_LIMIT = 262144;

const OBSERVED_TYPES = new Set(["session.created","session.updated","session.deleted","session.status","session.idle","session.error","message.updated","message.part.updated","message.part.delta"]);
const APPROVAL_TYPES = new Set(["permission.asked","permission.replied","question.asked","question.replied","question.rejected"]);
const SYNC_DELIVERY_TYPES = new Set(["session.idle","session.status","session.error"]);
const SYNC_DELIVERY_PART_TYPES = new Set([]);
const SNAPSHOT_TYPES = new Set(["session.idle","session.error"]);
const SNAPSHOT_PART_TYPES = new Set([]);
const SNAPSHOT_CHAR_LIMIT = 16384;
const ENVELOPE_LIMIT = 524288;

const ENV_KEYS = ["TERM_PROGRAM","ITERM_SESSION_ID","TERM_SESSION_ID","TMUX","TMUX_PANE","KITTY_WINDOW_ID","__CFBundleIdentifier","PASEO_AGENT_ID","CONDUCTOR_WORKSPACE_NAME","CONDUCTOR_PORT","CURSOR_TRACE_ID","CMUX_WORKSPACE_ID","CMUX_SURFACE_ID","CMUX_SOCKET_PATH","OTTY_SOCKET","OTTY_PANE_ID","WINDOWSERVER_DISPLAY_UUID"];

const HEADER_KEYS = ["cwd","directory","path","worktree"];


const _SIDECAR_USER = process.env[`${_VI_ENV_PREFIX}_SERVER_USERNAME`] || _VI_AUTH_USERNAME;
const _SIDECAR_PASSWORD = process.env[`${_VI_ENV_PREFIX}_SERVER_PASSWORD`];
const _AUTH_HEADER = _SIDECAR_PASSWORD
  ? "Basic " + Buffer.from(`${_SIDECAR_USER}:${_SIDECAR_PASSWORD}`).toString("base64")
  : null;

function sendTextToSocket(text) {
  return new Promise((resolve) => {
    let settled = false;
    let wrote = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    try {
      const sock = new Socket();
      sock.on("error", () => settle(false));
      sock.on("close", () => settle(wrote));
      sock.on("connect", () => {
        try {
          sock.write(text);
          wrote = true;
          sock.end();
        } catch {
          sock.destroy();
          settle(false);
        }
      });
      sock.setTimeout(3000, () => { sock.destroy(); settle(false); });
      sock.connect({ path: SOCKET });
    } catch { settle(false); }
  });
}

function sendToSocket(json) {
  let text;
  try { text = JSON.stringify(json); } catch { return Promise.resolve(false); }
  return sendTextToSocket(text);
}

const VI_TAIL_BUFFER_BYTES = 1048576;
let viTailBridge;
let viTailGeneration = 0;
let viTailInFlight = false;

function viTailBridgeDispose() {
  const bridge = viTailBridge;
  viTailBridge = undefined;
  if (!bridge) return;
  try { bridge.worker.terminate(); } catch {}
}

function viTailBridgeInit() {
  if (viTailBridge !== undefined) return viTailBridge;
  viTailBridge = null;
  try {
    const { Worker } = require("worker_threads");
    const control = new Int32Array(new SharedArrayBuffer(12));
    const payload = new Uint8Array(new SharedArrayBuffer(VI_TAIL_BUFFER_BYTES));
    const worker = new Worker(`
      const { workerData } = require("worker_threads");
      const net = require("net");
      const control = new Int32Array(workerData.control);
      const payload = new Uint8Array(workerData.payload);
      function park() {
        for (;;) {
          const state = Atomics.load(control, 0);
          if (state === 1) return;
          Atomics.wait(control, 0, state);
        }
      }
      function pump() {
        park();
        const length = Atomics.load(control, 1);
        const generation = Atomics.load(control, 2);
        let settled = false;
        let wrote = false;
        const done = (ok) => {
          if (settled) return;
          settled = true;
          if (Atomics.load(control, 2) !== generation) return setImmediate(pump);
          Atomics.store(control, 0, ok ? 2 : 3);
          Atomics.notify(control, 0);
          setImmediate(pump);
        };
        try {
          const body = Buffer.from(payload.buffer, 0, length).toString("utf8");
          const sock = net.connect({ path: workerData.socket }, () => {
            try { sock.write(body); wrote = true; sock.end(); }
            catch { sock.destroy(); done(false); }
          });
          sock.on("close", () => done(wrote));
          sock.on("error", () => done(false));
          sock.setTimeout(3000, () => { sock.destroy(); done(false); });
        } catch { done(false); }
      }
      pump();
    `, {
      eval: true,
      workerData: { control: control.buffer, payload: payload.buffer, socket: SOCKET },
    });
    worker.unref();
    const invalidate = () => { if (viTailBridge?.worker === worker) viTailBridgeDispose(); };
    worker.on("error", invalidate);
    worker.on("exit", invalidate);
    viTailBridge = { control, payload, worker };
  } catch {
    viTailBridge = undefined;
  }
  return viTailBridge ?? null;
}

function sendTextToSocketSync(text) {
  if (viTailInFlight) return false;
  const bridge = viTailBridgeInit();
  if (!bridge) return false;
  let bytes;
  try { bytes = Buffer.from(text, "utf8"); } catch { return false; }
  if (bytes.length === 0 || bytes.length > bridge.payload.length) return false;

  viTailInFlight = true;
  try {
    const generation = ++viTailGeneration;
    bridge.payload.set(bytes);
    Atomics.store(bridge.control, 1, bytes.length);
    Atomics.store(bridge.control, 2, generation);
    Atomics.store(bridge.control, 0, 1);
    Atomics.notify(bridge.control, 0);
    const deadline = Date.now() + 3000;
    for (;;) {
      const state = Atomics.load(bridge.control, 0);
      if ((state === 2 || state === 3)
          && Atomics.load(bridge.control, 2) === generation) {
        Atomics.store(bridge.control, 0, 0);
        Atomics.notify(bridge.control, 0);
        return state === 2;
      }
      if (Date.now() >= deadline) {
        viTailBridgeDispose();
        return false;
      }
      Atomics.wait(bridge.control, 0, state, 50);
    }
  } finally {
    viTailInFlight = false;
  }
}

function sendToSocketSync(json) {
  let text;
  try { text = JSON.stringify(json); } catch { return false; }
  return sendTextToSocketSync(text);
}

function sendAndWaitResponse(json, timeoutMs = 300000) {
  return new Promise((resolve) => {
    let settled = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    try {
      const sock = new Socket();
      let buf = "";
      sock.on("error", () => settle(null));
      sock.on("data", (data) => { buf += data.toString(); });
      sock.on("end", () => {
        try { settle(JSON.parse(buf)); } catch { settle(null); }
      });
      sock.on("connect", () => {
        try {
          sock.write(JSON.stringify(json));
        } catch {
          sock.destroy();
          settle(null);
        }
      });
      sock.setTimeout(timeoutMs, () => { sock.destroy(); settle(null); });
      sock.connect({ path: SOCKET });
    } catch { settle(null); }
  });
}

function startAwaitWaiter(record, timeoutMs = 300000) {
  let settled = false;
  let frameWritten = false;
  let settleFn = (_value) => {};
  const promise = new Promise((resolve) => {
    settleFn = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
  });
  const close = () => {};
  const handle = {
    writeSettle(_state) {},
    close,
    release(_state) { settleFn({ released: true, state: _state || "canceled" }); },
  };
  try {
    const sock = new Socket();
    let buf = Buffer.alloc(0);
    const awaitKey = record && record._await ? record._await.key : "";
    const closeSock = () => { try { sock.end(); } catch { sock.destroy(); } };
    const writeSettle = (state, to) => {
      if (!to) return;
      try {
        const json = Buffer.from(JSON.stringify({
          _vibe_wire: 2,
          _settle: { to, state },
        }));
        const frame = Buffer.alloc(4 + json.length);
        frame.writeUInt32BE(json.length, 0);
        json.copy(frame, 4);
        sock.write(frame);
      } catch {}
    };
    const finishReleased = (state) => {
      settleFn({ released: true, state: state || "canceled" });
    };
    handle.writeSettle = (state) => writeSettle(state, awaitKey);
    handle.close = closeSock;
    handle.release = (state) => {
      if (settled) return;
      writeSettle(state || "canceled", awaitKey);
      finishReleased(state || "canceled");
      closeSock();
    };
    const tryRead = () => {
      if (buf.length < 4) return;
      const n = buf.readUInt32BE(0);
      if (n > 524288 || buf.length < 4 + n) return;
      const payload = buf.subarray(4, 4 + n);
      buf = buf.subarray(4 + n);
      let obj;
      try { obj = JSON.parse(payload.toString("utf8")); } catch {
        finishReleased("canceled");
        return;
      }
      if (!obj || !obj._reply) {
        finishReleased("canceled");
        return;
      }
      settleFn({
        reply: obj._reply,
        settle: (state) => writeSettle(state, obj._reply.to),
        close: closeSock,
      });
    };
    sock.on("error", () => {
      settleFn(frameWritten ? { released: true, state: "canceled" } : null);
    });
    sock.on("data", (chunk) => {
      buf = Buffer.concat([buf, chunk]);
      tryRead();
    });
    sock.on("end", () => {
      if (!settled) {
        settleFn(frameWritten ? { released: true, state: "canceled" } : null);
      }
    });
    sock.on("connect", () => {
      if (settled) {
        closeSock();
        return;
      }
      try {
        const json = Buffer.from(
          typeof record === "string" ? record : JSON.stringify(record)
        );
        const frame = Buffer.alloc(4 + json.length);
        frame.writeUInt32BE(json.length, 0);
        json.copy(frame, 4);
        const magic = Buffer.concat([
          Buffer.from([0x00]),
          Buffer.from("vibe_wire2"),
          Buffer.from([0x0A]),
        ]);
        sock.write(Buffer.concat([magic, frame]));
        frameWritten = true;
      } catch {
        sock.destroy();
        settleFn(frameWritten ? { released: true, state: "canceled" } : null);
      }
    });
    sock.setTimeout(timeoutMs, () => {
      if (frameWritten) {
        writeSettle("expired", awaitKey);
        finishReleased("expired");
      } else {
        settleFn(null);
      }
      sock.destroy();
    });
    sock.connect({ path: SOCKET });
  } catch {
    settleFn(null);
  }
  return { promise, handle };
}

function sendAwaitAndWaitReply(record, timeoutMs = 300000) {
  return startAwaitWaiter(record, timeoutMs).promise;
}


let detectedTty = null;
try {
  const { execSync } = require("child_process");
  let walkPid = process.pid;
  for (let i = 0; i < 8; i++) {
    const info = execSync(`ps -o tty=,ppid= -p ${walkPid}`, { timeout: 1000 }).toString().trim();
    const parts = info.split(/\s+/);
    const tty = parts[0], ppid = parseInt(parts[1]);
    if (tty && tty !== "??" && tty !== "?") { detectedTty = `/dev/${tty}`; break; }
    if (!ppid || ppid <= 1) break;
    walkPid = ppid;
  }
} catch {}

function collectEnv() {
  const env = {};
  for (const k of ENV_KEYS) { if (process.env[k]) env[k] = process.env[k]; }
  if (process.env[`${_VI_ENV_PREFIX}_CLIENT`] === "desktop" && _VI_DESKTOP_BUNDLE_ID && !env.__CFBundleIdentifier) {
    env.__CFBundleIdentifier = _VI_DESKTOP_BUNDLE_ID;
  }
  return env;
}

export default async ({ client, serverUrl, directory }) => {
  const pid = process.pid;
  const serverOrigin = serverUrl?.origin || "http://127.0.0.1:4096";
  const serverPort = parseInt(serverUrl?.port) || 4096;

  function buildHeaders(cwd) {
    const headers = { "Content-Type": "application/json" };
    if (_AUTH_HEADER) headers.Authorization = _AUTH_HEADER;
    const dir = cwd || directory;
    if (dir) headers[_VI_DIRECTORY_HEADER] = encodeURIComponent(dir);
    return headers;
  }

  async function postReply(path, body, cwd) {
    try {
      const response = await fetch(`${serverOrigin}${path}`, {
        method: "POST", headers: buildHeaders(cwd), body: JSON.stringify(body),
      });
      if (response?.ok) return response;
    } catch {}
    const shouldUseClientFallback = !_AUTH_HEADER && serverPort === 4096;
    if (!shouldUseClientFallback) return null;
    try {
      const rawClient = client?._client;
      if (!rawClient?.post) return null;
      return await rawClient.post({ url: path, headers: buildHeaders(cwd), body });
    } catch { return null; }
  }

  async function fetchSessionInfo(sessionId, cwd) {
    const path = `/session/${encodeURIComponent(sessionId)}`;
    try {
      const response = await fetch(`${serverOrigin}${path}`, {
        method: "GET", headers: buildHeaders(cwd),
      });
      if (response?.ok) return await response.json();
    } catch {}
    const shouldUseClientFallback = !_AUTH_HEADER && serverPort === 4096;
    if (!shouldUseClientFallback) return null;
    try {
      const rawClient = client?._client;
      if (!rawClient?.get) return null;
      const result = await rawClient.get({ url: path, headers: buildHeaders(cwd) });
      return result?.data || result || null;
    } catch { return null; }
  }

  const seenEvents = new Map();
  const partBuffers = new Map();
  const assistantText = new Map();
  const fetchedInfo = new Map();
  
  const sessionCwd = new Map();

  function rememberSessionCwd(info) {
    if (!info?.id || !info.directory) return;
    sessionCwd.set(info.id, String(info.directory).slice(0, 4096));
    if (sessionCwd.size > 200) sessionCwd.delete(sessionCwd.keys().next().value);
  }

  
  function cleanupSeen(now) {
    if (seenEvents.size <= 500) return;
    const cutoff = now - 10 * 60 * 1000;
    for (const [key, ts] of seenEvents) {
      if (ts < cutoff || seenEvents.size > 800) seenEvents.delete(key);
      if (seenEvents.size <= 500) break;
    }
  }

  function eventKey(ev) {
    if (ev?.id) return `id:${ev.id}`;
    const p = ev?.properties || {};
    const part = p.part || {};
    const status = p.status?.type || part.state?.status || "";
    return [
      "fallback", ev?.type || "", p.sessionID || p.info?.sessionID || part.sessionID || p.info?.id || "",
      p.messageID || p.info?.id || part.messageID || "", p.partID || part.id || p.id || "", status,
    ].join(":");
  }

  function shouldProcessEvent(ev) {
    const key = eventKey(ev);
    if (!key) return true;
    if (seenEvents.has(key)) return false;
    const now = Date.now();
    seenEvents.set(key, now);
    cleanupSeen(now);
    return true;
  }

  function normalizeSyncEventType(type) {
    return (type || "").replace(/\.\d+$/, "");
  }

  function syncEventToBusEvent(syncEvent) {
    const type = normalizeSyncEventType(syncEvent?.type);
    if (!isObserved(type) && !APPROVAL_TYPES.has(type)) return null;
    return { id: syncEvent.id, type, properties: syncEvent.data || {} };
  }

  function isObserved(type) {
    return OBSERVED_TYPES.has(type);
  }

  
  function sessionOf(ev) {
    const p = ev.properties || {};
    return p.info?.sessionID || p.sessionID || p.part?.sessionID || p.info?.id || "";
  }

  
  function absorbDelta(p) {
    if (!p?.sessionID || !p?.partID || p.field !== "text") return;
    const key = `${p.sessionID}:${p.partID}`;
    const current = partBuffers.get(key) || "";
    if (current.length >= SNAPSHOT_CHAR_LIMIT) return;
    const next = (current + (p.delta || "")).slice(0, SNAPSHOT_CHAR_LIMIT);
    partBuffers.set(key, next);
    if (partBuffers.size > 200) partBuffers.delete(partBuffers.keys().next().value);
    assistantText.set(p.sessionID, next);
    if (assistantText.size > 200) assistantText.delete(assistantText.keys().next().value);
  }

  
  function isSyncDelivery(ev) {
    if (!SYNC_DELIVERY_TYPES.has(ev.type)) return false;
    if (ev.type !== "message.part.updated") return true;
    return SYNC_DELIVERY_PART_TYPES.has(ev.properties?.part?.type);
  }

  function wantsSnapshot(ev) {
    if (!SNAPSHOT_TYPES.has(ev.type)) return false;
    if (ev.type !== "message.part.updated") return true;
    return SNAPSHOT_PART_TYPES.has(ev.properties?.part?.type);
  }

  
  function projectKeys(source, keys) {
    if (!source || typeof source !== "object" || Array.isArray(source)) return {};
    const out = {};
    for (const k of keys) { if (source[k] !== undefined) out[k] = source[k]; }
    return out;
  }

  
  function envelope(ev, tail, hydration) {
    const key = String(sessionOf(ev) || "");
    if (!key) return null;
    const header = projectKeys(ev.properties?.info, HEADER_KEYS);
    
    const transport = {
      ppid: pid,
      cwd: directory,
      env: collectEnv(),
      tty: detectedTty,
      server_port: serverPort,
    };
    if (hydration) transport.hydration = true;
    const snapshot = tail ? assistantText.get(key) : null;
    if (snapshot) transport.assistant_text = snapshot;
    const info = fetchedInfo.get(key);
    if (info) transport.session_info = info;
    const body = {
      _vibe_wire: WIRE,
      _source: _VI_SOURCE,
      _session_key: key,
      _transport: transport,
      _raw: { header, event: { type: ev.type, data: ev.properties || {} } },
    };
    
    try {
      if (Buffer.byteLength(JSON.stringify(body._raw)) > RAW_LIMIT) {
        body._raw = { header: {}, event: { type: ev.type } };
        body._truncated = true;
      }
    } catch {
      body._raw = { header: {}, event: { type: ev.type } };
      body._truncated = true;
    }
    return body;
  }

  
  function serializeEnvelope(body) {
    const encode = () => { try { return JSON.stringify(body); } catch { return null; } };
    let text = encode();
    if (text === null) return null;
    if (Buffer.byteLength(text) <= ENVELOPE_LIMIT) return text;
    if (body._transport.assistant_text) {
      delete body._transport.assistant_text;
      body._truncated = true;
      text = encode();
      if (text === null) return null;
      if (Buffer.byteLength(text) <= ENVELOPE_LIMIT) return text;
    }
    body._raw = { header: {}, event: { type: body._raw?.event?.type || "" } };
    body._truncated = true;
    text = encode();
    if (text === null || Buffer.byteLength(text) > ENVELOPE_LIMIT) return null;
    return text;
  }

  
  function needsSessionInfo(info) {
    if (!info?.id || fetchedInfo.has(info.id)) return false;
    if (!info.directory || !info.title) return true;
    return !(info.parentID || info.parentId || info.parent_id);
  }

  async function ensureSessionInfo(ev) {
    if (ev.type !== "session.created" && ev.type !== "session.updated") return false;
    const info = ev.properties?.info;
    if (!needsSessionInfo(info)) return false;
    const fetched = await fetchSessionInfo(info.id, info.directory);
    if (!fetched) return false;
    fetchedInfo.set(info.id, fetched);
    if (fetchedInfo.size > 200) fetchedInfo.delete(fetchedInfo.keys().next().value);
    rememberSessionCwd(fetched);
    return true;
  }

  
  const termProg = process.env.TERM_PROGRAM || "";
  const needsTitleFallback = ["ghostty", "xterm-ghostty"].includes(termProg)
    && process.env.__CFBundleIdentifier === "com.mitchellh.ghostty"
    && !process.env.TMUX;
  const terminalTitlePreference = `${require("os").homedir()}/.vibe-island/cache/terminal-title-management`;
  let displayTitle = null;

  function managesTerminalTitles() {
    try { return require("fs").readFileSync(terminalTitlePreference, "utf8").trim() !== "0"; }
    catch { return true; }
  }

  function setTabTitle(sessionId, cwd, text) {
    if (!needsTitleFallback || !managesTerminalTitles()) return;
    const project = (cwd || directory || process.env.PWD || "session").split("/").pop() || "session";
    const prefix = String(sessionId).slice(0, 16);
    if (text) displayTitle = text.replace(/\n/g, " ").slice(0, 30);
    const title = displayTitle
      ? `${project} · ${displayTitle} · ${prefix}`
      : `${project} · ${prefix}`;
    if (detectedTty) {
      try { require("fs").writeFileSync(detectedTty, `\x1b]2;${title}\x07`); } catch {}
    }
    try {
      const fs = require("fs");
      const osc2Dir = `${require("os").homedir()}/.vibe-island/cache/osc2-titles`;
      try { fs.mkdirSync(osc2Dir, { recursive: true }); } catch {}
      fs.writeFileSync(`${osc2Dir}/${prefix}`, displayTitle || "");
    } catch {}
  }

  function noteTitleAnchor(ev) {
    const p = ev.properties || {};
    if (ev.type === "session.created" && p.info?.id) {
      setTabTitle(p.info.id, p.info.directory, null);
      return;
    }
    if (ev.type === "session.updated" && p.info?.id) {
      const title = p.info.title;
      if (title && !title.startsWith("New session")) setTabTitle(p.info.id, p.info.directory, title);
    }
  }

  const awaitLedger = new Map();

  function askedLedgerKey(ev) {
    const id = ev.properties?.id || ev.properties?.requestID || ev.id || "";
    return `${sessionOf(ev)}:${id}`;
  }

  function awaitEnvelope(ev) {
    const body = envelope(ev, false, false);
    if (!body) return null;
    const crypto = require("crypto");
    const key = (crypto.randomUUID ? crypto.randomUUID() : crypto.randomBytes(16).toString("hex"))
      .replace(/-/g, "");
    body._vibe_wire = 2;
    body._await = { key, deadline_ms: 300000 };
    return body;
  }

  function releaseAwaitIfOpen(event, state) {
    const key = askedLedgerKey(event);
    const entry = awaitLedger.get(key);
    if (!entry?.handle) return;
    entry.handle.release(state);
    awaitLedger.set(key, { claimed: true, settle: state });
  }

  async function dispatchAsked(event) {
    const body = awaitEnvelope(event);
    if (!body) return;
    const key = askedLedgerKey(event);
    const prior = awaitLedger.get(key);
    if (prior?.settle) {
      const replay = await sendAwaitAndWaitReply(body);
      if (replay && !replay.released) {
        replay.settle(prior.settle);
        replay.close();
      }
      return;
    }
    if (prior?.claimed) return;
    const waiter = startAwaitWaiter(body);
    awaitLedger.set(key, { claimed: true, handle: waiter.handle });
    const awaitSession = await waiter.promise;
    if (awaitSession?.released) {
      if (!awaitLedger.get(key)?.settle) {
        awaitLedger.set(key, { claimed: true, settle: awaitSession.state || "canceled" });
      }
      return;
    }
    if (!awaitSession) {
      awaitLedger.delete(key);
      return;
    }
    // 岛先答：立刻丢掉 handle，避免 permission.replied 回声把已收到的 _reply 再 cancel。
    awaitLedger.set(key, { claimed: true });
    const deliver = awaitSession.reply?.deliver;
    const cwd = sessionCwd.get(sessionOf(event)) || directory;
    let state = "failed";
    if (deliver?.mode === "post" && typeof deliver.origin_path === "string") {
      const posted = await postReply(deliver.origin_path, deliver.body ?? {}, cwd);
      state = posted ? "delivered" : "failed";
    } else if (deliver?.mode === "respond") {
      state = "delivered";
    }
    awaitLedger.set(key, { claimed: true, settle: state });
    awaitSession.settle(state);
    awaitSession.close();
  }

  async function dispatchEvent(event) {
    if (!event || !shouldProcessEvent(event)) return;
    if (APPROVAL_TYPES.has(event.type)) {
      if (event.type === "permission.asked" || event.type === "question.asked") {
        void dispatchAsked(event);
        return;
      }
      if (
        event.type === "permission.replied"
        || event.type === "question.replied"
        || event.type === "question.rejected"
      ) {
        releaseAwaitIfOpen(event, "canceled");
      }
      return;
    }
    if (!isObserved(event.type)) return;
    if (event.type === "message.part.delta") {
      absorbDelta(event.properties);
      return;
    }
    noteTitleAnchor(event);
    rememberSessionCwd(event.properties?.info);
    
    await emitEnvelope(event, false);
    
    if (await ensureSessionInfo(event)) await emitEnvelope(event, true);
  }

  async function emitEnvelope(event, hydration) {
    const body = envelope(event, wantsSnapshot(event), hydration);
    if (!body) return;
    const text = serializeEnvelope(body);
    if (text === null) return;
    
    if (isSyncDelivery(event)) {
      if (sendTextToSocketSync(text)) return;
      
      body._transport.sync_fallback = true;
      const retry = serializeEnvelope(body);
      if (retry !== null) { await sendTextToSocket(retry); return; }
    }
    await sendTextToSocket(text);
  }

  function shouldConsumeGlobalEvent(globalEvent) {
    if (!globalEvent?.payload) return false;
    if (globalEvent.directory && directory && globalEvent.directory !== directory) return false;
    return true;
  }

  function handleGlobalSseChunk(chunk) {
    const data = chunk.split(/\r?\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart())
      .join("\n");
    if (!data) return;
    try {
      const globalEvent = JSON.parse(data);
      if (!shouldConsumeGlobalEvent(globalEvent)) return;
      const payload = globalEvent.payload || {};
      if (payload.type !== "sync") return;
      const event = syncEventToBusEvent(payload.syncEvent);
      if (event) void dispatchEvent(event);
    } catch {}
  }

  
  async function startGlobalEventBridge() {
    const shouldStart = _VI_GLOBAL_EVENT_BRIDGE === "always"
      || process.env[`${_VI_ENV_PREFIX}_CLIENT`] === "desktop"
      || Boolean(_AUTH_HEADER)
      || (serverUrl?.port && serverPort !== 4096);
    if (!shouldStart) return;

    const bridgeDelay = (ms) => new Promise((resolve) => {
      const timer = setTimeout(resolve, ms);
      if (timer?.unref) timer.unref();
    });

    let delay = 1000;
    while (true) {
      try {
        const response = await fetch(`${serverOrigin}/global/event`, {
          method: "GET",
          headers: buildHeaders(directory),
        });
        if (!response?.ok || !response.body) throw new Error("global event unavailable");
        delay = 1000;
        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          buffer = buffer.replace(/\r\n/g, "\n");
          let idx;
          while ((idx = buffer.indexOf("\n\n")) !== -1) {
            const chunk = buffer.slice(0, idx);
            buffer = buffer.slice(idx + 2);
            handleGlobalSseChunk(chunk);
          }
        }
      } catch {}
      await bridgeDelay(delay);
      delay = Math.min(delay * 2, 30000);
    }
  }

  void startGlobalEventBridge();

  return {
    "event": async ({ event }) => {
      await dispatchEvent(event);
    },
    "shell.env": async (input, output) => {
      for (const v of ENV_KEYS) {
        if (process.env[v]) output.env["_VI_" + v] = process.env[v];
      }
    },
  };
};