[[session]]
name = "streamliner"
path = "~/github/glg/streamliner"
startup_command = ". ~/.config/sesh/scripts/streamliner.sh"

[[session]]
name = "Client-Solutions-Experience"
path = "~/github/glg/Client-Solutions-Experience"
startup_command = "gh dash"

[[session]]
name = "consultations-api"
path = "~/github/glg/consultations-api"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"

[[session]]
name = "settings-api"
path = "~/github/glg/settings-api"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"
