[[session]]
name = "streamliner"
path = "~/github/glg/streamliner"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"

[[session]]
name = "consultations-api"
path = "~/github/glg/consultations-api"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"

[[session]]
name = "settings-api"
path = "~/github/glg/settings-api"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"

[[session]]
name = "prism"
path = "~/github/glg/prism"
startup_command = ". ~/.config/sesh/scripts/node-app.sh"
